/**
 * Generates llms.txt (index) and llms-full.txt (full doc bundle) from the
 * docs tree, per https://llmstxt.org. Both files ship in the npm package so
 * AI agents working in consuming projects can read current, version-matched
 * documentation straight from node_modules.
 *
 * Usage:
 *   node scripts/build-llms.js           # write llms.txt + llms-full.txt
 *   node scripts/build-llms.js --check   # exit 1 if committed files are stale
 *
 * Keeping this honest: the source of truth stays in AGENT_GUIDE.md, README,
 * and docs/** (which AGENTS.md's artifact matrix already forces to be kept
 * current). CI runs --check, so a docs change that forgets to regenerate
 * fails the build instead of shipping stale agent docs.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const RAW_BASE = 'https://raw.githubusercontent.com/sathvikc/lume-js/main';

// docs/*.md carry `<!-- lume:key -->value<!-- /lume:key -->` markers so
// scripts/sync-docs.js can keep facts current. Those markers are internal
// bookkeeping — an agent reading llms-full.txt should see plain prose, not
// Lume's templating syntax, so strip the comment wrappers and keep the
// already-resolved value between them.
const MARKER_RE = /<!--\s*(lume:[\w-]+)\s*-->([\s\S]*?)<!--\s*\/\1\s*-->/g;
const stripMarkers = content => content.replace(MARKER_RE, (_, __, value) => value.trim());

// Ordered manifest: what goes into llms-full.txt and gets linked in llms.txt.
// docs/manifest.json is the single authored structure — it also drives the
// docs/README index and nav footers (scripts/sync-docs.js). Section titles
// and entry order here follow the manifest, not a second hand-kept list.
const SECTIONS = JSON.parse(fs.readFileSync(path.join(root, 'docs', 'manifest.json'), 'utf8'))
  .sections.map(section => ({
    title: section.title,
    files: section.entries.map(entry => [entry.path, entry.description]),
  }));

const HEADER = `# Lume.js

> Minimal reactive state management using only standard JavaScript and HTML —
> no custom syntax, no build step, no framework lock-in. 1.46 KB universal
> core (state/batch), 2.66 KB with DOM binding (bindDom/effect). Reactivity
> that follows web standards: stores are Proxies over plain objects, DOM
> binding is declarative via valid data-* attributes, updates are
> microtask-batched per store with an explicit batch() escape hatch for
> cross-store writes.

Version: ${pkg.version}. Install: \`npm install lume-js\` or import from
\`https://cdn.jsdelivr.net/npm/lume-js/dist/index.min.mjs\`.

Key facts agents get wrong without reading the docs: arrays and nested
objects must be REPLACED, never mutated in place (reference equality);
nested objects need explicit state() wrapping; updates flush on the next
microtask, not synchronously; effects only track keys read synchronously;
data-* attribute values are state keys, never expressions.
`;

function generateIndex() {
  let out = HEADER;
  for (const section of SECTIONS) {
    out += `\n## ${section.title}\n\n`;
    for (const [file, desc] of section.files) {
      out += `- [${file}](${RAW_BASE}/${file}): ${desc}\n`;
    }
  }
  out += `\n## Optional\n\n- [llms-full.txt](${RAW_BASE}/llms-full.txt): every file above concatenated into one document\n`;
  return out;
}

function generateFull() {
  let out = HEADER;
  out += '\nThis file is the full documentation bundle: every guide, tutorial, and\nAPI page concatenated. Generated by scripts/build-llms.js — do not edit.\n';
  for (const section of SECTIONS) {
    for (const [file] of section.files) {
      const content = stripMarkers(fs.readFileSync(path.join(root, file), 'utf8')).trim();
      out += `\n\n${'='.repeat(72)}\nFILE: ${file}\n${'='.repeat(72)}\n\n${content}\n`;
    }
  }
  return out;
}

const outputs = {
  'llms.txt': generateIndex(),
  'llms-full.txt': generateFull(),
};

if (process.argv.includes('--check')) {
  const stale = Object.entries(outputs).filter(([name, content]) => {
    const file = path.join(root, name);
    return !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content;
  }).map(([name]) => name);
  if (stale.length > 0) {
    console.error(`Stale agent docs: ${stale.join(', ')}. Run \`npm run llms\` and commit the result.`);
    process.exit(1);
  }
  console.log('llms.txt and llms-full.txt are up to date.');
} else {
  for (const [name, content] of Object.entries(outputs)) {
    fs.writeFileSync(path.join(root, name), content);
    console.log(`Wrote ${name} (${(content.length / 1024).toFixed(1)} KB)`);
  }
}
